name: release
on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven
      run: mvn -B -DskipTests -ntp install
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to GHCR
      run: mvn -B -DskipTests=true -DskipITs=true -ntp -P docker docker:build docker:push
